DROP DATABASE Universidad
GO

CREATE DATABASE Universidad
GO

USE Universidad;
GO

--////// TABLAS //////--

--ASIGNATURAS
IF OBJECT_ID('Asignaturas') IS NOT NULL
	DROP TABLE Asignaturas;
GO

CREATE TABLE Asignaturas
(
Id INT IDENTITY(1,1),
Codigo VARCHAR(20) NOT NULL,
Nombre VARCHAR(50) NOT NULL,
Creditos TINYINT NOT NULL,
CONSTRAINT PK_ASIG PRIMARY KEY (Id),
CONSTRAINT UQ_COD_ASIG UNIQUE (Codigo),
CONSTRAINT UQ_NOM_ASIG UNIQUE (Codigo)
)
--SELECT * FROM Asignaturas
GO


--DOCENTES
IF OBJECT_ID('Docentes') IS NOT NULL
	DROP TABLE Docentes;
GO

CREATE TABLE Docentes
(
Id INT IDENTITY(1,1),
Codigo VARCHAR(20) NOT NULL,
Nombres VARCHAR(30) NOT NULL,
Apellidos VARCHAR(30) NOT NULL,
CONSTRAINT PK_DOC PRIMARY KEY (Id),
Id_Asignatura INT NOT NULL
CONSTRAINT FK_ASIG_DOC FOREIGN KEY REFERENCES Asignaturas(Id)
ON UPDATE CASCADE
ON DELETE CASCADE
)
--SELECT * FROM Docentes
GO

--ESTUDIANTES
IF OBJECT_ID('Estudiantes') IS NOT NULL
	DROP TABLE Estudiantes;
GO

CREATE TABLE Estudiantes
(
Id INT IDENTITY(1,1),
Codigo VARCHAR(20) NOT NULL,
Nombres VARCHAR(30) NOT NULL,
Apellidos VARCHAR(30) NOT NULL,
Semestre VARCHAR(10) NOT NULL,
Carrera VARCHAR(50) NOT NULL,
CONSTRAINT PK_EST PRIMARY KEY (Id),
Id_Asignatura INT NOT NULL
CONSTRAINT FK_EST_ASIG FOREIGN KEY REFERENCES Asignaturas(Id)
ON UPDATE CASCADE
ON DELETE CASCADE
)
--SELECT * FROM Estudiantes
GO

--RECORD ACADEMICO
IF OBJECT_ID('RecordAcademico') IS NOT NULL
	DROP TABLE RecordAcademico;
GO

CREATE TABLE RecordAcademico
(
Id INT IDENTITY(1,1),
Codigo VARCHAR(20) NOT NULL,
Fecha DATE NOT NULL,
Periodo VARCHAR(20) NOT NULL,
Nota1 DECIMAL(3,2)  NOT NULL,
Nota2 DECIMAL (3,2) NOT NULL,
Promedio AS (Nota1 + Nota2) / 2,
CONSTRAINT PK_RA PRIMARY KEY (Id),
CONSTRAINT UQ_COD_RA UNIQUE (Codigo),
Id_Estudiante INT NOT NULL
CONSTRAINT FK_RA_EST FOREIGN KEY REFERENCES Estudiantes(Id),
Id_Docente INT NOT NULL
CONSTRAINT FK_RA_DOC FOREIGN KEY REFERENCES Docentes(Id)
ON UPDATE CASCADE
ON DELETE CASCADE
)
--SELECT * FROM RecordAcademico
GO

